backend:
  name: github
  repo: ChrisDunkley/portfolio-v3

media_folder: static/assets
public_folder: assets

collections:
  - name: music
    label: Music
    folder: src/music
    summary: "{{artist}} - {{title}}"
    slug: "{{artist}}-{{slug}}"
    create: true
    delete: true
    fields:
      - { name: artist, label: Artist }
      - { name: title, label: Title }
      - { name: cover, label: Cover, widget: image }
      - { name: date, label: Date added, widget: date }
      - { name: release-year, label: Year of release }
      - { name: body, label: Body, widget: markdown, required: false }
  - name: notes
    label: Notes
    folder: src/notes
    create: true
    delete: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { name: body, label: Body, widget: markdown }
  